import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import ts from 'typescript';
import {dungeonStep,dungeonBusy,freshDungeon} from '../app/dungeon-engine.ts';
import {heroTotalAttributes} from '../app/hero-rules.ts';
import {vitalStats,combatStats} from '../app/vitals-engine.ts';
import {DIVINE_EQUIPMENT} from '../app/divine-equipment.ts';
import {addInventoryItem} from '../app/inventory-layout.ts';
import {settleCaravanIdle} from '../app/caravan-idle.ts';
import {advanceTrade, freshTrade} from '../app/trade-engine.ts';
const source=readFileSync(new URL('../app/game-v15.tsx',import.meta.url),'utf8');
const code=source.slice(source.indexOf('function applyDungeon('),source.indexOf('function inheritMerchantPrototype('));
const context=vm.createContext({dungeonStep,dungeonBusy,freshDungeon,heroTotalAttributes,vitalStats,combatStats,DIVINE_EQUIPMENT,addInventoryItem,settleCaravanIdle,advanceTrade,addLog:(l,m)=>[m,...l],grantXp:(u,x)=>({...u,xp:u.xp+x})});
vm.runInContext(ts.transpileModule(code,{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText,context);
const game=()=>({hero:{templateId:'hero',level:1,str:150,agi:15,vit:20,intel:10,xp:0,hp:80,mp:40,equip:{}},inventory:[],dungeon:freshDungeon(),gold:0,credit:0,kills:0,logs:[],trade:freshTrade(),idleStamp:1000,mercs:[],active:[]});
test('integrated kill pays XP gold and one item into actual inventory',()=>{const s=context.applyDungeon(game(),'start',1000,'wolf');const r=context.applyDungeon(s,'normal',1100,undefined,0,0);assert.equal(r.hero.xp,100);assert.equal(r.gold,80);assert.equal(r.inventory[0].name,'高級神仙棒');assert.equal(r.hero.hp,80);assert.equal(context.applyDungeon(r,'normal',1101).gold,80)});
test('integrated full bag never overwrites existing gear',()=>{const s=game();s.inventory=Array.from({length:20},(_,i)=>({uid:String(i)}));const r=context.applyDungeon(context.applyDungeon(s,'start',1000),'normal',1100,undefined,0,0);assert.equal(r.inventory.length,20);assert.equal(r.inventory[0].uid,'0');assert.equal(r.gold,80);assert.match(r.logs[0],/背包已滿/)});
test('healing suppresses passive income including completion tick',()=>{const s=game();s.dungeon={...freshDungeon(),status:'recovering',stamp:1000};s.hero.hp=79;const r=context.settleMerchantGame(s,2000);assert.equal(r.gold,0);assert.equal(r.credit,0);assert.equal(r.dungeon.status,'idle');assert.equal(r.idleStamp,2000);const n=context.settleMerchantGame(r,3000);assert.equal(n.gold,10);assert.equal(n.credit,5)});
test('paused voyage preserves progress even subsecond ticks',()=>{const s=game();s.trade.caravan={startedAt:500};let r=context.applyDungeon(s,'start',1000);r=context.settleMerchantGame(r,1500);r=context.settleMerchantGame(r,2000);assert.equal(r.trade.caravan.startedAt,1500);assert.equal(r.hero.xp,100)});
test('react interval has cleanup and sampled randomness outside updater',()=>{assert.match(source,/clearInterval\(timer\)/);assert.match(source,/const now=Date.now\(\),roll=Math.random\(\),choice=Math.random\(\);/);assert.match(source,/next.dungeon=\{\.\.\.freshDungeon\(\),status:'recovering'/)});
