import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import '../scripts/audit-fresh-prologue.mjs';
const require=createRequire(import.meta.url);
const {freshGame}=require('../app/game-hero-factory.ts');
const {worldCities}=require('../app/v15-data.ts');
const {createNpcController}=require('../app/game-npc-controller.ts');
const {npcById,npcGreeting,awardNpcAffinity,hasNpcAffinityReward}=require('../app/npc-dialogue.ts');
const {hanyangNpcOptions,hanyangNpcGreeting}=require('../app/hanyang-npc-dialogue.ts');
const noop=()=>{};

test('actual NPC controller advances handoffs only for the current NPC and story option',()=>{
  for(const [step,id,nextStep,flag] of [
    ['caravan-delivery','wang-deokchang','return','caravanCargoDelivered'],
    ['return','kim-seongho','departure',null],
    ['departure','kim-seongho','completed','worldMapUnlocked'],
  ]) {
    const state={...freshGame('handoff'),hanyangPrologueStep:step};
    if(step!=='caravan-delivery')state.hanyangPrologueFlags={...state.hanyangPrologueFlags,
      caravanCargoDelivered:true,merchantPriceRevealed:true};
    const npc=npcById(id),option=hanyangNpcOptions(state,id)[0];
    for(const oldOption of npc.options)assert.equal(action(state,npc,oldOption).hanyangPrologueStep,step);
    const other=npcById(id==='kim-seongho'?'wang-deokchang':'kim-seongho');
    assert.equal(action(state,other,option).hanyangPrologueStep,step);
    const next=action(state,npc,option);
    assert.equal(next.hanyangPrologueStep,nextStep);
    if(flag)assert.equal(next.hanyangPrologueFlags[flag],true);
    else assert.deepEqual(next.hanyangPrologueFlags,state.hanyangPrologueFlags);
    const replay=action(next,npc,option);
    assert.equal(replay.hanyangPrologueStep,nextStep);
    assert.equal(replay.gold,next.gold);
    assert.deepEqual(replay.materials,next.materials);
    assert.deepEqual(replay.inventory,next.inventory);
    assert.deepEqual(replay.medicines,next.medicines);
  }
});

test('opening dialogue uses story greetings, retains normal fallbacks and never awards progression',()=>{
  for(const [step,id] of [['caravan-delivery','wang-deokchang'],['return','kim-seongho'],
    ['completed','wang-deokchang'],['arrival','heo-muncheol']]) {
    let game={...freshGame('greeting'),hanyangPrologueStep:step},line,active;
    const before=structuredClone(game),npc=npcById(id);
    const expected=hanyangNpcGreeting(game,id)||npcGreeting(game,npc);
    const controller=createNpcController({game,currentCity:worldCities.find(city=>city.id===game.city),
      setGame:update=>{game=update(game);},setNotice:noop,setActiveTab:noop,setCityService:noop,
      setActiveNpcId:value=>{active=value;},setNpcOpeningLine:value=>{line=value;}});
    controller.openNpcDialogue(id);
    assert.equal(line,expected);
    assert.equal(active,id);
    assert.ok(game.npcProgress.history.some(entry=>entry.npcId===id&&entry.text===`${npc.name}：${expected}`));
    for(const key of ['gold','inventory','materials','medicines','hanyangPrologueStep','hanyangPrologueFlags'])
      assert.deepEqual(game[key],before[key]);
  }
});

test('first caravan quest grants the calibrated sword and supplies only on actual completion',()=>{
  const npc=npcById('kim-seongho'),start=npc.options.find(option=>option.quest==='start');
  // This completion choice is generated by npc-dialogue-panel, not npc.options.
  const complete={label:'回報任務',reply:'做得好，這是約定的謝禮。',quest:'complete'};
  const initial=freshGame('caravan-quest'),started=action(initial,npc,start);
  assert.equal(started.inventory.length,initial.inventory.length);
  const incomplete=action(started,npc,complete);
  assert.equal(incomplete.inventory.length,initial.inventory.length);
  assert.equal(incomplete.gold,started.gold);
  const eligible={...started,starterDeliveryKills:npc.quest.target};
  const rewarded=action(eligible,npc,complete),sword=rewarded.inventory.at(-1);
  assert.equal(rewarded.inventory.length,eligible.inventory.length+1);
  assert.equal(sword.atk,4);
  assert.equal(sword.requiredLevel,1);
  assert.equal(rewarded.hanyangPrologueStep,'first-sale');
  assert.equal(rewarded.onboardingStep,'completed');
  assert.equal(rewarded.hanyangPrologueFlags.starterSupplyGranted,true);
  const replay=action(rewarded,npc,complete);
  for(const key of ['gold','inventory','medicines','materials'])assert.deepEqual(replay[key],rewarded[key]);
});

function action(state,npc,option){
  let result=state;
  createNpcController({game:state,currentCity:worldCities.find(city=>city.id===state.city),setGame:update=>{result=update(result);},setNotice:noop,setActiveNpcId:noop,setActiveTab:noop,setCityService:noop,setNpcOpeningLine:noop}).handleNpcAction({npc,option});
  return result;
}

test('previously claimed merchant affinity cannot disable the separate crisis choice',()=>{
  const npc=npcById('wang-deokchang'),talk=npc.options.find(option=>option.label==='談談商道');
  const state=awardNpcAffinity({...freshGame('主線對話'),hanyangPrologueStep:'caravan-crisis'},npc,talk);
  const before=structuredClone(state),options=hanyangNpcOptions(state,npc.id);
  assert.equal(hasNpcAffinityReward(state.npcProgress,npc,talk),true);
  assert.equal(options.length,1);
  assert.equal(options[0].prologueStep,'caravan-crisis');
  assert.equal(hasNpcAffinityReward(state.npcProgress,npc,options[0]),false);
  assert.match(hanyangNpcGreeting(state,npc.id),/黑巾斥候/);
  const next=action(state,npc,options[0]);
  assert.equal(next.hanyangPrologueStep,'bandit-trial');
  assert.deepEqual(next.npcProgress.affinity,state.npcProgress.affinity);
  assert.deepEqual(next.npcProgress.affinityChoices,state.npcProgress.affinityChoices);
  assert.equal(next.gold,state.gold);
  assert.equal(next.logs.filter(line=>line.includes('王德昌：黑巾斥候堵住')).length,1);
  const replay=action(next,npc,options[0]);
  assert.equal(replay.hanyangPrologueStep,'bandit-trial');
  assert.equal(replay.logs.filter(line=>line.includes('王德昌：黑巾斥候堵住')).length,1);
  assert.deepEqual(state,before);
});

test('unrelated NPC, market services and old dialogue never advance the crisis',()=>{
  const state={...freshGame('不跳任務'),hanyangPrologueStep:'caravan-crisis'},merchant=npcById('wang-deokchang');
  for(const option of merchant.options)assert.equal(action(state,merchant,option).hanyangPrologueStep,'caravan-crisis',option.label);
  const chief=npcById('kim-seongho');
  assert.equal(action(state,chief,hanyangNpcOptions(state,merchant.id)[0]).hanyangPrologueStep,'caravan-crisis');
  for(const step of ['arrival','medicine','formation','bandit-trial','completed']){
    const other={...state,hanyangPrologueStep:step};
    assert.equal(action(other,merchant,hanyangNpcOptions(state,merchant.id)[0]).hanyangPrologueStep,step);
  }
});

test('story options are only offered for their actual NPC and current handoff step',()=>{
  for(const [step,id] of [['caravan-crisis','wang-deokchang'],['caravan-delivery','wang-deokchang'],['return','kim-seongho'],['departure','kim-seongho']]){
    const state={hanyangPrologueStep:step};
    assert.equal(hanyangNpcOptions(state,id)[0].prologueStep,step);
    assert.ok(hanyangNpcGreeting(state,id));
    assert.deepEqual(hanyangNpcOptions(state,'heo-muncheol'),[]);
  }
  assert.deepEqual(hanyangNpcOptions({hanyangPrologueStep:'completed'},'wang-deokchang'),[]);
  assert.equal(hanyangNpcGreeting({hanyangPrologueStep:'completed'},'wang-deokchang'),null);
});
