/* eslint-disable next/no-img-element */
import {useEffect,useRef} from 'react';
import {Progress} from '@/components/ui/progress';
import {DUNGEONS,type DungeonState,type RealtimeBattleUnitState} from './dungeon-engine';
import {vitalStats} from './vitals-engine';
import type {CaravanMember} from './caravan-status';
import {createBattleEffects} from './battle-effects';
import {Shield,Frown} from 'lucide-react';

const monsterArt:Record<string,string>={狸貓:'/assets/sprites/newbie-raccoon-v1.png',倭寇:'/assets/characters/char_049_pirate_skeleton_bow_R.png',鐵炮倭寇:'/assets/characters/char_053_pirate_skeleton_cannon_R.png',山賊:'/assets/characters/char_056_pirate_skeleton_captain_N.png',海賊:'/assets/characters/char_057_pirate_skeleton_captain_R.png',鐵鉤海賊:'/assets/characters/char_055_pirate_skeleton_captain_D.png',赤賊:'/assets/characters/char_054_pirate_skeleton_captain_A.png',巫女:'/assets/characters/char_052_pirate_skeleton_cannon_N.png',司令武女:'/assets/characters/char_052_pirate_skeleton_cannon_N.png','詭異的小販':'/assets/characters/char_054_pirate_skeleton_captain_A.png','詭異的獨角鬼(火)':'/assets/characters/char_057_pirate_skeleton_captain_R.png','詭異的獨角鬼(水)':'/assets/characters/char_049_pirate_skeleton_bow_R.png','詭異的獨角鬼(雷)':'/assets/characters/char_053_pirate_skeleton_cannon_R.png','詭異的獨角鬼(風)':'/assets/characters/char_056_pirate_skeleton_captain_N.png',阿魯塔:'/assets/characters/char_055_pirate_skeleton_captain_D.png','死靈武女(強)':'/assets/characters/char_052_pirate_skeleton_cannon_N.png','巫女(強)':'/assets/characters/char_052_pirate_skeleton_cannon_N.png',神漢男巫:'/assets/characters/char_049_pirate_skeleton_bow_R.png',邪靈巫師:'/assets/characters/char_053_pirate_skeleton_cannon_N.png',赤賊頭目:'/assets/characters/char_054_pirate_skeleton_captain_A.png',狂風阿魯塔:'/assets/monsters/gale-altur.gif',黃金海星:'/assets/monsters/golden-starfish.gif'};

export function BattleArena({state,hero,party}:{state:DungeonState;hero:CaravanMember & {nation?:string};party:CaravanMember[]}){
 const root=useRef<HTMLDivElement>(null),effects=useRef<ReturnType<typeof createBattleEffects>|null>(null);
 const seen=useRef(state.eventSerial||0),spawn=useRef(state.spawnSerial||0);
 useEffect(()=>{if(!root.current)return;effects.current=createBattleEffects(root.current);return()=>{effects.current?.clear();effects.current=null}},[]);
 useEffect(()=>{if(spawn.current!==(state.spawnSerial||0)){effects.current?.spawn();spawn.current=state.spawnSerial||0}for(const event of state.events||[])if(event.id>seen.current){effects.current?.triggerBattleAnimation({attacker:event.attacker,target:event.target,damage:event.amount,skill:event.skill,critical:event.critical});seen.current=event.id}},[state.events,state.spawnSerial]);

 const monster=DUNGEONS[state.key],v=vitalStats(hero),players=state.realtime?.players||[],enemies=state.realtime?.enemies||[];
 const playerSlots=Array.from({length:12},(_,index)=>{const member=party[index],live=member?players.find(unit=>unit.id===member.uid):undefined;return member?{member,live}:null});
 const enemySlots=Array.from({length:12},(_,index)=>enemies[index]||({id:`enemy-${index+1}`,side:'enemy',hp:state.status==='fighting'?monster.hp:0,maxHp:monster.hp,atk:monster.atk,def:0,attackInterval:1.5,cooldown:0,mp:0,position:{row:Math.floor(index/4),col:index%4}} as RealtimeBattleUnitState));
 const shieldActive=monster.name==='狂風阿魯塔'&&(state.enemyShieldUntil||0)>Date.now(),fearActive=(state.fearUntil||0)>Date.now();

 return <div className={'impact-stage formation-battle-stage'+(state.status==='fighting'?' impact-stage-fighting':'')} ref={root} aria-label="12 對 12 即時自動戰鬥">
  <section className="battle-squad battle-squad-player" data-hit="hero" data-motion="hero"><header><div><strong>我方商隊</strong><small>後排 col 0　→　前排 col 3</small></div><span>{players.filter(unit=>unit.hp>0).length||party.filter(unit=>(unit.hp||0)>0).length}／{party.length} 存活</span></header><div className="battle-unit-grid">{playerSlots.map((slot,index)=>{const position=slot?.live?.position||{row:Math.floor(index/4),col:index%4};return slot?<article key={slot.member.uid} className={(slot.live?.hp??slot.member.hp??0)<=0?'unit-defeated':''}><img src={slot.member.image} alt=""/><div><strong>{slot.member.name}</strong><small>Lv.{slot.member.level}・{index===0?'主角':'傭兵'}・[{position.row},{position.col}]</small></div><label>HP {Math.max(0,slot.live?.hp??slot.member.hp??0).toLocaleString()}<Progress value={Math.max(0,(slot.live?.hp??slot.member.hp??0)/(slot.live?.maxHp??slot.member.maxHp??1)*100)}/></label><span>MP {slot.live?.mp??(index===0?v.mp:slot.member.mp||0)}・攻速 {(slot.live?.attackInterval??1.5).toFixed(1)}s</span></article>:<article className="battle-unit-empty" key={'player-empty-'+index}><b>{index+1}</b><span>[{position.row},{position.col}] 未配置</span></article>})}</div><div className="impact-overlay" data-popup="hero"/></section>
  <span className="impact-versus" aria-hidden="true">VS</span>
  <section className="battle-squad battle-squad-enemy" data-hit="enemy" data-motion="enemy" data-spawn="enemy"><header><div><strong>{monster.name}部隊</strong><small>前排 col 0　→　後排 col 3</small></div><span>{enemySlots.filter(unit=>unit.hp>0).length}／12 存活</span></header><div className="battle-unit-grid">{enemySlots.map((unit,index)=><article key={unit.id} className={unit.hp<=0?'unit-defeated':''}><span className="battle-unit-monster"><img src={monsterArt[monster.name]||'/assets/sprites/enemy-idle.png'} alt=""/>{shieldActive&&<i title="白虎盾・防禦 +30%"><Shield size={12}/></i>}{fearActive&&<i title="恐懼・防禦 -20%"><Frown size={12}/></i>}</span><div><strong>{monster.name}</strong><small>#{index+1}・Lv.{monster.level}・[{unit.position.row},{unit.position.col}]</small></div><label>HP {Math.max(0,unit.hp).toLocaleString()}<Progress value={Math.max(0,unit.hp/unit.maxHp*100)}/></label><span>MP {unit.mp}・攻速 {unit.attackInterval.toFixed(1)}s</span></article>)}</div><div className="impact-overlay" data-popup="enemy"/></section>
 </div>;
}
