"use client";
import { FIRST_CARAVAN_QUEST_ID,FIRST_CARAVAN_TARGET } from "./game-progression-view";
import type { GameViewModel } from './use-game-controller';

type Props = Pick<GameViewModel, "activeTab" | "game" | "hanyangStep" | "tutorialCityLocked" | "tutorialTrialLocked">;

export function GameOnboarding({ activeTab, game, hanyangStep, tutorialCityLocked, tutorialTrialLocked }: Props) {
return <>{activeTab !== "map" && game.hanyangPrologueStep === "completed" && (tutorialTrialLocked || tutorialCityLocked) && <aside className="village-onboarding-buddy" aria-live="polite"><span className="village-onboarding-avatar" aria-hidden="true">🧭</span><div><strong>小嚮導・米米</strong><p>{tutorialTrialLocked ? "不好！黑巾斥候正在搶奪貨物，任務已自動接受，請立即迎戰！" : "一個人守不住商路，請立刻前往傭兵公會招募普通傭兵。"}</p><small>{tutorialTrialLocked ? "前往新手村郊外・黑巾斥候" : "傭兵公會已開放・招募第一名普通傭兵"}</small></div></aside>}
{game.hanyangPrologueStep !== "completed" && <aside className="village-onboarding-buddy hanyang-prologue-buddy" aria-live="polite"><span className="village-onboarding-avatar" aria-hidden="true">🧭</span><div><strong>小嚮導・米米</strong><p>{game.hanyangPrologueStep === "arrival" ? (game.npcProgress.activeQuests.includes(FIRST_CARAVAN_QUEST_ID) && game.starterDeliveryKills >= FIRST_CARAVAN_TARGET ? "驛路已清出來了，先回村長處回報並領取裝備。" : "村長正在村口等你，先去聽聽他的緊急委託。") : game.hanyangPrologueStep === "outskirts" ? "先到新手村郊外擊敗偷糧狸，取得第一批可以出售的戰利品。" : game.hanyangPrologueStep === "first-sale" ? ((game.npcProgress.activeQuests.includes(FIRST_CARAVAN_QUEST_ID) && game.starterDeliveryKills >= FIRST_CARAVAN_TARGET && !game.inventory.some(item => item.name === "商路短劍") && !Object.values(game.hero.equip).some(item => item?.name === "商路短劍")) ? "驛路已清出來了，先回村長處回報並領取裝備。" : "偷糧狸戰利品帶回來了，先穿戴剛取得的裝備，再把材料賣掉。") : game.hanyangPrologueStep === "journey-fund" ? "老商人準備了一筆啟程資金，回漢陽找他領取。" : game.hanyangPrologueStep === "medicine" ? "啟程資金已備妥，前往藥店實際購買一瓶金創藥。" : game.hanyangPrologueStep === "guild" ? "一個人守不住商路，前往傭兵公會招募一名夥伴。" : game.hanyangPrologueStep === "formation" ? "傭兵已加入商團，打開隊伍介面確認他在出戰名單中。" : game.hanyangPrologueStep === "caravan-crisis" ? "北邊商路出事了，先找老商人了解貨物被搶的經過。" : game.hanyangPrologueStep === "bandit-trial" ? "精英黑巾斥候就在新手村郊外；他不是 Boss，和第一名夥伴一起把他擊退。" : "商路已恢復，回到漢陽看看老商人怎麼說。"}</p><small>序章引導・{hanyangStep.title}</small></div></aside>}</>;
}
