import type { EquipmentKind } from './equipment-slots';

export type ThunderForgeId = 'thunderBoots' | 'thunderBow' | 'azureArmor' | 'azureHelm' | 'azureGloves' | 'azureBoots' | 'azureBelt' | 'chiyouArmor' | 'chiyouHelm' | 'chiyouGloves' | 'chiyouBoots' | 'chiyouBelt' | 'amaterasuStaff' | 'amaterasuGloves' | 'amaterasuArmor' | 'amaterasuBelt' | 'amaterasuBoots';
export type MythicSet = 'thunder' | 'azure' | 'chiyou' | 'amaterasu';
type Affix = { id:string; name:string; text:string; color:string; stat:string; value:number };
export type MythicForgeItem = { id:ThunderForgeId; set:MythicSet; name:string; slot:EquipmentKind; atk:number; def:number; hp:number; image?:string; skill?:string; bonus:{str:number;agi:number;intel:number;vit:number}; magic:Affix[]; needs:Record<string,number> };

const noBonus={str:0,agi:0,intel:0,vit:0};
const forge = (item:MythicForgeItem) => item;
export const THUNDER_FORGE_ITEMS:Record<ThunderForgeId,MythicForgeItem>={
 thunderBoots:forge({id:'thunderBoots',set:'thunder',name:'T10 雷神迅影靴',slot:'boots',atk:30,def:20,hp:120,bonus:{...noBonus,agi:25},magic:[{id:'thunder-agi',name:'雷神迅影',text:'敏捷 +15%',color:'#71cfff',stat:'agi',value:15}],needs:{'喵兒的尾巴':20,'小型雷之屬性石':80}}),
 thunderBow:forge({id:'thunderBow',set:'thunder',name:'T10 雷神穿雲弓',slot:'weapon',atk:220,def:10,hp:0,bonus:noBonus,magic:[{id:'thunder-atk',name:'雷霆穿雲',text:'攻擊 +20%',color:'#71cfff',stat:'atk',value:20}],needs:{'雷電的箭矢':20,'深淵的精髓':5}}),
 azureArmor:forge({id:'azureArmor',set:'azure',name:'T10 青龍盔甲',slot:'armor',atk:0,def:420,hp:2400,image:'/assets/equipment/azure-dragon/azure-dragon-armor.gif',bonus:{...noBonus,vit:80},magic:[{id:'azure-armor',name:'青龍庇護',text:'生命 +15%',color:'#90d4ad',stat:'hp',value:15}],needs:{'鹿亞之角':10,'小型雷之屬性石':80,'精氣之珠碎片':12}}),
 azureHelm:forge({id:'azureHelm',set:'azure',name:'T10 青龍頭盔',slot:'helm',atk:0,def:260,hp:900,image:'/assets/equipment/azure-dragon/azure-dragon-helm.jpg',bonus:{...noBonus,vit:40},magic:[{id:'azure-helm',name:'龍甲格擋',text:'防禦 +20%',color:'#90d4ad',stat:'def',value:20}],needs:{'青龍頭盔':1,'深淵的精髓':5,'小型雷之屬性石':40}}),
 azureGloves:forge({id:'azureGloves',set:'azure',name:'T10 青龍護手',slot:'gloves',atk:110,def:90,hp:0,image:'/assets/equipment/azure-dragon/azure-dragon-gloves.gif',bonus:{...noBonus,str:45},magic:[{id:'azure-gloves',name:'蒼龍爪勁',text:'攻擊 +12%',color:'#90d4ad',stat:'atk',value:12}],needs:{'雷電的箭矢':12,'深淵的精髓':5,'小型雷之屬性石':50}}),
 azureBoots:forge({id:'azureBoots',set:'azure',name:'T10 青龍護腿',slot:'boots',atk:0,def:170,hp:700,image:'/assets/equipment/azure-dragon/azure-dragon-boots.gif',bonus:{...noBonus,agi:60},magic:[{id:'azure-boots',name:'青雲步',text:'敏捷 +15%',color:'#90d4ad',stat:'agi',value:15}],needs:{'喵兒的尾巴':12,'精氣之珠碎片':10,'小型雷之屬性石':50}}),
 azureBelt:forge({id:'azureBelt',set:'azure',name:'T10 青龍腰帶',slot:'amulet',atk:0,def:120,hp:1400,image:'/assets/equipment/azure-dragon/azure-dragon-belt.gif',bonus:{...noBonus,intel:50},magic:[{id:'azure-belt',name:'龍脈回響',text:'生命 +10%',color:'#90d4ad',stat:'hp',value:10}],needs:{'鹿亞之角':6,'[玉衡]咒術秘訣':1,'小型雷之屬性石':60}}),
 chiyouArmor:forge({id:'chiyouArmor',set:'chiyou',name:'T10 蚩尤戰甲',slot:'armor',atk:0,def:460,hp:2100,image:'/assets/equipment/chiyou/chiyou-armor.png',bonus:{...noBonus,vit:70},magic:[{id:'chiyou-armor',name:'戰神鐵壁',text:'防禦 +18%',color:'#e99a69',stat:'def',value:18}],needs:{'深淵的精髓':10,'古代神獸之精髓':2,'小型憤怒精髓':8}}),
 chiyouHelm:forge({id:'chiyouHelm',set:'chiyou',name:'T10 蚩尤戰盔',slot:'helm',atk:0,def:290,hp:800,image:'/assets/equipment/chiyou/chiyou-helm.png',bonus:{...noBonus,str:35},magic:[{id:'chiyou-helm',name:'不屈戰意',text:'攻擊 +10%',color:'#e99a69',stat:'atk',value:10}],needs:{'古代神獸之精髓':1,'小型憤怒精髓':6,'被封印的力量碎片':1}}),
 chiyouGloves:forge({id:'chiyouGloves',set:'chiyou',name:'T10 蚩尤護手',slot:'gloves',atk:160,def:80,hp:0,image:'/assets/equipment/chiyou/chiyou-gloves.png',bonus:{...noBonus,str:65},magic:[{id:'chiyou-gloves',name:'破軍',text:'攻擊 +18%',color:'#e99a69',stat:'atk',value:18}],needs:{'赤賊頭目的矛':1,'深淵的精髓':6,'小型憤怒精髓':5}}),
 chiyouBoots:forge({id:'chiyouBoots',set:'chiyou',name:'T10 蚩尤護腿',slot:'boots',atk:0,def:190,hp:650,image:'/assets/equipment/chiyou/chiyou-boots.png',bonus:{...noBonus,agi:55},magic:[{id:'chiyou-boots',name:'戰場奔襲',text:'敏捷 +12%',color:'#e99a69',stat:'agi',value:12}],needs:{'狂虎之爪':3,'生命的精髓':5,'小型憤怒精髓':5}}),
 chiyouBelt:forge({id:'chiyouBelt',set:'chiyou',name:'T10 蚩尤腰帶',slot:'amulet',atk:70,def:130,hp:1100,image:'/assets/equipment/chiyou/chiyou-belt.png',bonus:{...noBonus,intel:45},magic:[{id:'chiyou-belt',name:'戰魂回流',text:'生命 +10%',color:'#e99a69',stat:'hp',value:10}],needs:{'神獸之根源(白虎)':1,'深淵的精髓':5,'小型憤怒精髓':6}}),
 amaterasuStaff:forge({id:'amaterasuStaff',set:'amaterasu',name:'T10 天照神杖',slot:'weapon',atk:320,def:20,hp:0,image:'/assets/equipment/amaterasu/amaterasu-staff.gif',skill:'天照大神的凝視：天照五件套集齊後，攻擊有 3% 機率造成主角攻擊力 ×10 暴擊，並使敵人恐懼 5 秒（防禦 -20%）。',bonus:{...noBonus,intel:120},magic:[{id:'amaterasu-staff',name:'日輪法印',text:'攻擊 +25%',color:'#82d9ff',stat:'atk',value:25}],needs:{'天照的手套':1,'深淵的精髓':8,'小型雷之屬性石':80}}),
 amaterasuGloves:forge({id:'amaterasuGloves',set:'amaterasu',name:'T10 天照護手',slot:'gloves',atk:60,def:80,hp:300,image:'/assets/equipment/amaterasu/amaterasu-gloves.gif',bonus:{...noBonus,intel:75},magic:[{id:'amaterasu-gloves',name:'靈光導引',text:'生命 +8%',color:'#82d9ff',stat:'hp',value:8}],needs:{'精氣之珠碎片':20,'深淵的精髓':5,'小型雷之屬性石':50}}),
 amaterasuArmor:forge({id:'amaterasuArmor',set:'amaterasu',name:'T10 天照神甲',slot:'armor',atk:0,def:310,hp:1600,image:'/assets/equipment/amaterasu/amaterasu-armor.gif',bonus:{...noBonus,intel:90,vit:30},magic:[{id:'amaterasu-armor',name:'天照結界',text:'防禦 +15%',color:'#82d9ff',stat:'def',value:15}],needs:{'古代神獸之精髓':1,'深淵的精髓':10,'小型雷之屬性石':70}}),
 amaterasuBelt:forge({id:'amaterasuBelt',set:'amaterasu',name:'T10 天照神環',slot:'amulet',atk:0,def:100,hp:1000,image:'/assets/equipment/amaterasu/amaterasu-belt.gif',bonus:{...noBonus,intel:100},magic:[{id:'amaterasu-belt',name:'神託',text:'生命 +12%',color:'#82d9ff',stat:'hp',value:12}],needs:{'[玉衡]咒術秘訣':1,'被封印的力量碎片':1,'精氣之珠碎片':18}}),
 amaterasuBoots:forge({id:'amaterasuBoots',set:'amaterasu',name:'T10 天照神靴',slot:'boots',atk:0,def:150,hp:600,image:'/assets/equipment/amaterasu/amaterasu-boots.gif',bonus:{...noBonus,intel:65,agi:35},magic:[{id:'amaterasu-boots',name:'日行千里',text:'敏捷 +10%',color:'#82d9ff',stat:'agi',value:10}],needs:{'狂風花':10,'小型風之屬性石':20,'小型雷之屬性石':40}}),
};
export const THUNDER_FORGE_RECIPES=Object.values(THUNDER_FORGE_ITEMS);
export const MYTHIC_ART_BY_NAME=Object.fromEntries(THUNDER_FORGE_RECIPES.filter(item=>item.image).map(item=>[item.name,item.image!])) as Record<string,string>;
export const mythicSetPieceCount=(names:Iterable<string>,set:MythicSet)=>{const setNames=new Set(THUNDER_FORGE_RECIPES.filter(item=>item.set===set).map(item=>item.name));return new Set([...names].filter(name=>setNames.has(name))).size};
